### PR TITLE
change styling

### PR DESCRIPTION
**Pull request by miaadele**
styling complete for proposals list view
needs to be connected to db

### CODE REVIEW

**Review by v3ceban — CHANGES_REQUESTED** [review]
Looks good. Nice usage of server components. A couple of things:
- **src/app/(auth-user)/proposals/[proposalID]/page.jsx**: Search params need to be awaited in Next15. Pls change defult export function to async and await **searchParams**
- **src/app/(auth-user)/proposals/page.jsx**:
  - **SidebarTrigger** doesn't close sidebar. Is it intended? If so, should the button be removed?
  - I't seems that **Pagination** part is hardcoded and will not work if more proposals are fetched
  - **Sidebar** filters also don't seem to filter anything.
  - **Sidebar** filters need a way to unset selected radio buttons
- What is the point of **columns.jsx** and **data-table.jsx** files? They don't seem to be used anywhere...  Pls make sure to cleanup unused code.

**Comment by v3ceban** [comment]
As per new merge requirements, other team members were added as reviewers

**Comment by miaadele** [comment]
@v3ceban 

- changed the default function to async and awaited the params
- Pagination is implemented but commented out lines 20-46 of proposals/page.jsx because the projects themselves are not being fetched yet
- sidebar filter functionality will be incorporated in the next sprint, not in the scope of this sprint
- removed those files, had originally left them in case Jason wanted to incorporate the commented out code for his functions

**Review by v3ceban — APPROVED** [review]
Good!

**Review by marleyyvon — APPROVED** [review]

**Review by jcisneros1999 — APPROVED** [review]
Looks good.

**Review by vaniaggarwal — APPROVED** [review]

**Pull request merged**
