### PR TITLE
Added new footer and adjusted nav to match

### PR DESCRIPTION
**Pull request by marleyyvon**
New footer with adjusted nav to match. Will have to fix the margins on each to account for darkmode and other backgrounds. Overall this is a start- will need to think about all css and card dependancies on page.jsx.

### CODE REVIEW

**Comment by v3ceban** [comment]
Looks good. Some logic-based things needs to be fixed:
1. Please consider reusing existing AuthButton component in Navbar. This will allow us to change the behavior of one component and propagate it to all places it's used in, rather than going and looking for 100500 different implemenations.
2. Don't mix up tailwind classes with css modules. All classNames in styles/AuthButton.module.css should be converted to tailwind and used directly in AuthButton.jsx. This way we can change the styles of this button based on usecase when/if needed.
3. Please add hardcoded tailwind colors in tailwind config, so they can be reused later without the need to search for the hex code in the codebase.
4. Logout option needs to be present in navbar when user is logged in.

**Review by v3ceban — CHANGES_REQUESTED** [review]
Looks good. Some logic-based things needs to be fixed:

1. Please consider reusing existing AuthButton component in Navbar. This will allow us to change the behavior of one component and propagate it to all places it's used in, rather than going and looking for 100500 different implemenations.
2. Don't mix up tailwind classes with css modules. All classNames in styles/AuthButton.module.css should be converted to tailwind and used directly in AuthButton.jsx. This way we can change the styles of this button based on usecase when/if needed.
3. Please add hardcoded tailwind colors in tailwind config, so they can be reused later without the need to search for the hex code in the codebase.
4. Logout option needs to be present in navbar when user is logged in.

**Comment by vaniaggarwal** [comment]
Some things I noticed: 
- there's like a "." before it lists the email
- the red of the box with the sign out and email is a little in your face, so maybe make it the same color as the nav bar
- the black of the scu logo is odd against the background color, potentially make it white? 
- the routing for the account portion of the nav bar got messed up 

Otherwise it looks amazing!

**Review by vaniaggarwal — CHANGES_REQUESTED** [review]
Some things I noticed:

- there's like a "." before it lists the email
- the red of the box with the sign out and email is a little in your face, so maybe make it the same color as the nav bar
- the black of the scu logo is odd against the background color, potentially make it white?
- the routing for the account portion of the nav bar got messed up

Otherwise it looks amazing!

**Pull request merged**
