### PR TITLE
Added Previous Works Section To Faculty Profile

### PR DESCRIPTION
**Pull request by jcisneros1999**
Title is self explanatory, cleaned up so stuff and also added Dr. Atkinson to faculty table to allow for real testing.

### CODE REVIEW

**Review by miaadele — APPROVED** [review]
Looks good! Need to remove the paragraph tags from the archived projects

**Review by vaniaggarwal — CHANGES_REQUESTED** [review]
For our intents seems to work, an issue I noticed we should address: 
- <p> tags in the description of the project
issue we don't actually need to address, but I'm bringing up anyway
- "read more" doesn't work

**Comment by v3ceban** [comment]
>     * tags in the description of the project
+1 to what @vaniaggarwal said. Possible ways to address:
- Use `dangerouslySetInnerHTML` prop [link](https://react.dev/reference/react-dom/components/common#dangerously-setting-the-inner-html)
- Use `str.replace(regex, "")`, where `regex` is something like `/<\/?[^>]+>/g` and `str` is the string you pull up from API.

**Review by v3ceban — APPROVED** [review]
Approving if problems resolved

**Pull request merged**
